name: linux
on:
  workflow_dispatch:
  push:
    branches: [ main, restructure ]
  pull_request:
    branches: [ main, restructure ]
jobs:
  all:
    name: all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: sudo apt-get install gcc-aarch64-linux-gnu
    - run: sudo apt-get install binutils-aarch64-linux-gnu
    - run: sudo apt-get install g++-aarch64-linux-gnu
    - run: sudo apt-get install device-tree-compiler
    - run: make -j3 build/stages/linux/linux.image
    - run: make -j3 build/stages/linux/linux.image.macho
    - run: make -j3 build/stages/linux/linux.image{artifact}
    - run: make -j3 build/stages/linux/linux.image.macho{artifact}
