name: m1n1
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  all:
    name: all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set env variables
      uses: ./github/env/
    - run: sudo apt-get install gcc-aarch64-linux-gnu
    - run: sudo apt-get install binutils-aarch64-linux-gnu
    - run: sudo apt-get install g++-aarch64-linux-gnu
    - run: sudo apt-get install device-tree-compiler
    - run: make -kj3 build/stages/m1n1/m1n1.macho
    - run: make -kj3 build/stages/m1n1/m1n1.macho{artifact}
    - run: make -kj3 build/stages/m1n1/m1n1.macho.image
    - run: make -kj3 build/stages/m1n1/m1n1.macho.image{artifact}
