name: modules
on:
  workflow_dispatch:
  push:
    branches: [ main, dcp, update ]
  pull_request:
    branches: [ main, dcp, update ]
jobs:
  all:
    name: all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set env variables
      uses: ./g/github/env/
    - run: sudo apt-get update
    - run: sudo apt-get install autopoint
    - run: sudo apt-get install lzop
    - run: sudo apt-get install libgmp-dev libmpfr-dev libmpc-dev
    - run: sudo apt-get install libipc-run-perl libfile-slurp-perl
    - run: sudo apt-get install qemu-user qemu-user-static binfmt-support
    - run: sudo apt-get install gettext
    - run: sudo apt-get install xz-utils
    - run: sudo apt-get install device-tree-compiler
    - run: sudo apt-get install libtool-bin
    - run: make -j13 build/toolchain/binutils-gdb/done/install
    - run: make -j13 build/linux/done/headers/install
    - run: make -j13 build/userspace/glibc/done/headers/install
    - run: make -j13 build/toolchain/gcc/done/gcc/install
    - run: rm -rf build/toolchain/gcc/gcc
    - run: make -j13 build/toolchain.tar
    - run: make -j13 build/userspace/glibc/done/glibc/install
    - run: make -j13 build/toolchain/gcc/done/libgcc/install
    - run: rm -rf build/toolchain/gcc/libgcc
    - run: make -j13 build/userspace/ncurses/done/install
    - run: make -j13 build/userspace/dialog/done/install
    - run: make -j13 build/userspace/screen/done/install
    - run: make -j13 build/userspace/procps/done/install
    - run: make -j13 build/userspace/busybox/done/install
    - run: make -j13 build/userspace/kexec-tools/done/install
    - run: make -j13 build/userspace/emacs/done/cross/install
    - run: make -j13 build/userspace/perl/done/install
    - run: make -j13 build/userspace/IPC-Run/done/install
    - run: make -j13 build/userspace/slurp/done/install
    - run: make -j13 build/userspace/libnl/done/install
    - run: make -j13 build/userspace/memtool/done/install
    - run: make -j13 build/userspace/libuuid/done/install
    - run: make -j13 build/userspace/json-c/done/install
    - run: make -j13 build/userspace/popt/done/install
    - run: make -j13 build/userspace/libblkid/done/install
    - run: make -j13 build/userspace/libaio/done/install
    - run: make -j13 build/userspace/lvm2/done/install
    - run: make -j13 build/userspace/openssl/done/install
    - run: make -j13 build/userspace/cryptsetup/done/install
    - run: make -j13 build/userspace/dtc/done/install
    - run: make -j13 build/userspace/wpa_supplicant/done/install
    - run: make -j13 build/bootloaders/m1n1/done/install
    - run: make -j13 build/bootloaders/barebox/done/install
    - run: make -j13 build/bootloaders/u-boot/done/install
    - run: make -j13 build/bootloaders/grub/done/install
    - run: make -j13 build/userspace/done/install
    - run: make -j13 build/userspace.tar
    - run: make -j13 build/linux/pearl.image
    - run: make -j13 build/linux/pearl.image.macho
    - run: rm -rf build/linux/linux
    - run: rm -rf build/linux/pearl
    - run: rm -rf build/linux/stage2
    - run: make -j13 build/userspace.tar.zstd{daily}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: make -j13 build/toolchain.tar.zstd{daily}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: make -j13 build/linux/pearl.image.zstd{daily}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: make -j13 build/linux/pearl.image.macho.zstd{daily}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: make -j13 build/pearl.pl{artifact}
