name: modules
on:
  workflow_dispatch:
  push:
    branches: [ main, restructure ]
  pull_request:
    branches: [ main, restructure ]
jobs:
  all:
    name: all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set env variables
      uses: ./g/github/env/
    - run: sudo apt-get install autopoint
    - run: sudo apt-get install lzop
    - run: sudo apt-get install libgmp-dev libmpfr-dev libmpc-dev
    - run: sudo apt-get install libipc-run-perl
    - run: make -j3 build/done/binutils-gdb/install
    - run: make -j3 build/done/gcc/stage1/install
    - run: make -j3 build/done/linux/headers/install
    - run: make -j3 build/done/glibc/stage1/install
    - run: make -j3 build/install-stage1.tar{artifact}
    - run: make -j3 build/done/gcc/gcc/install
    - run: make -j3 build/done/glibc/glibc/install
    - run: make -j3 build/install-stage2.tar{artifact}
    - run: make -j3 build/done/busybox/install
    - run: make -j3 build/done/kexec-tools/install
    - run: make -j3 build/done/ncurses/install
    - run: make -j3 build/done/emacs/cross/install
    - run: make -j3 build/done/perl/install
    - run: make -j3 build/done/libnl/install
    - run: make -j3 build/done/memtool/install
    - run: make -j3 build/done/libuuid/install
    - run: make -j3 build/done/json-c/install
    - run: make -j3 build/done/popt/install
    - run: make -j3 build/done/libblkid/install
    - run: make -j3 build/done/libaio/install
    - run: make -j3 build/done/lvm2/install
    - run: make -j3 build/done/openssl/install
    - run: make -j3 build/done/cryptsetup/install
    - run: make -j3 build/done/nvme-cli/install
    - run: make -j3 build/install-userspace.tar{artifact}
    - run: make -j3 build/done/linux/linux/image
    - run: make -j3 build/done/linux/linux/modules
    - run: make -j3 build/done/linux/stage2/image
    - run: make -j3 build/done/linux/stage2/modules
    - run: make -j3 build/done/linux/stage1/image
